plugins {
    id 'fabric-loom'
}

base {
    archivesName = "${rootProject.property('mod_id')}-fabric"
}

configurations {
    commonJava { canBeResolved = true; canBeConsumed = false }
    commonResources { canBeResolved = true; canBeConsumed = false }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.property('minecraft_version')}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${rootProject.property('fabric_loader_version')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.property('fabric_api_version')}"
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
    implementation project(':common')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn configurations.commonJava
    source configurations.commonJava
}

processResources {
    dependsOn configurations.commonResources
    from(configurations.commonResources)
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', rootProject.property('minecraft_version')
    filesMatching('fabric.mod.json') {
        expand version: project.version,
                minecraft_version: rootProject.property('minecraft_version'),
                fabric_loader_version: rootProject.property('fabric_loader_version'),
                mod_id: rootProject.property('mod_id'),
                mod_name: rootProject.property('mod_name'),
                mod_description: rootProject.property('mod_description'),
                mod_author: rootProject.property('mod_author'),
                mod_license: rootProject.property('mod_license')
    }
}

def minecraftMcpModId = project.rootProject.property('mod_id').toString()
loom {
    mixin {
        defaultRefmapName.set("${minecraftMcpModId}.refmap.json")
    }
}
