plugins {
    id 'fabric-loom'
}

base {
    archivesName = "${rootProject.property('mod_id')}-common"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.property('minecraft_version')}"
    mappings loom.officialMojangMappings()
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
}
