plugins {
    id 'java-library'
}

base {
    archivesName = "${rootProject.property('mod_id')}-common"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
}
